FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine AS build
WORKDIR /app

# copy all files from solution
COPY ./ ./

# Publish to 'out' directory single main project
RUN dotnet publish ApiDeploy/ApiDeploy.csproj -c Release -o out

# Create final repository
FROM mcr.microsoft.com/dotnet/runtime:3.1-alpine AS runtime
WORKDIR /app
LABEL maintainer="az"
RUN addgroup az && adduser -D -G az az
RUN chown -R az:az /app
USER az
# copy published files in destination folder
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "ApiDeploy.dll"]

# docker build -t sbraer/apideploy -f Dockerfile_deploy .
# docker push sbraer/apideploy
