apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-configmap-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-deployment-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-refreshconfigmap-role
rules:
- apiGroups: ["example.com"]
  resources: ["refreshconfigmaps"]
  verbs: ["watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-configmap
subjects:
- kind: ServiceAccount
  name: crd-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-configmap-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-deployment
subjects:
- kind: ServiceAccount
  name: crd-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-deployment-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-refreshconfigmap
subjects:
- kind: ServiceAccount
  name: crd-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-refreshconfigmap-role
  apiGroup: rbac.authorization.k8s.io
